### ISSUE TITLE
api 更新

### ISSUE THREAD

**Issue by jsonz1993** [jaywcjlove/cookie.js#2]
unescape 和 escape 已经被弃用。应该可以使用 encodeURI 和 decodeURI 代替？

**Comment by jaywcjlove** [comment]
@jsonz1993  👌

**Comment by jsonz1993** [comment]
还有一个小疑问。 我在 [mozilla](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/cookies/set) 上面看到文档，好像 `cookie.set(name, value, opts)` 中 `opts.secure`的值应该是`Boolean`类型的，[cookie.js scroll](https://github.com/jaywcjlove/cookie.js/blob/master/src/cookie.js#L47) 这里用的是空字符串， 是同个效果吗  疑问脸
